steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/code-practice-380104/lavender-snake", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/code-practice-380104/lavender-snake"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "lavender-snake",
        "--image",
        "gcr.io/code-practice-380104/lavender-snake",
        "--region",
        "us-west1",
      ]
images:
  - gcr.io/code-practice-380104/lavender-snake
