steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/code-practice-380104/code-practice-webapp", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/code-practice-380104/code-practice-webapp"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "code-practice-webapp",
        "--image",
        "gcr.io/code-practice-380104/code-practice-webapp",
        "--region",
        "us-west1",
      ]
images:
  - gcr.io/code-practice-380104/code-practice-webapp
