# build environment
FROM node:19-alpine as build
ENV NODE_VERSION 19.7.0
WORKDIR /app
COPY ./package*.json ./
ENV PATH /app/node_modules/.bin:$PATH

# build shared
WORKDIR /app/shared
COPY ./shared/package*.json ./
RUN npm ci 
WORKDIR /app
COPY ./shared ./shared
RUN npm run shared-build

# build server
WORKDIR /app/server
COPY ./server/package*.json ./
RUN npm ci --silent
WORKDIR /app
COPY ./server ./server
RUN npm run server-build

EXPOSE 3000
ENV NODE_ENV production
CMD [ "npm", "start" ]

# TODOproduction environment
# FROM nginx:stable-alpine
# COPY client/nginx.conf /etc/nginx/conf.d/configfile.template
# COPY --from=build /app/server/dist /usr/share/nginx/html
# ENV PORT 8080
# ENV HOST 0.0.0.0
# EXPOSE 8080
# #CMD ["nginx", "-g", "daemon off;"]
# CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
